### ISSUE TITLE
bug: cjs build doesn't work in cjs

### ISSUE THREAD

**Issue by roninjin10** [wagmi-dev/anvil.js#17]
There is a [cjs build](https://github.com/wagmi-dev/anvil.js/blob/main/packages/anvil.js/package.json#L13) but because `execa` is included and is a js library of type: module cjs doesn't work

**Comment by roninjin10** [comment]
https://github.com/sindresorhus/execa/issues/489

**Comment by roninjin10** [comment]
I could fix this via building execa in a build step before tsc is ran and making execa a devDep.  That's a bit hacky though.   This is easy to fix with most build tools by just bundling the node module too.

**Comment by roninjin10** [comment]
Another fix I could try is using `(await import('execa')` instead of importing it directly which should make it work in cjs

**Comment by fubhy** [comment]
Good catch. I'm strictly not using CJS at this point so I missed this.

My go-to solution for this is usually dynamic imports. Want to submit a PR for that?

**Comment by fubhy** [comment]
@roninjin10 Can you test the latest version?
